<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities [
<!ELEMENT expression (#PCDATA)>
<!ELEMENT maths (#PCDATA | expression | evaluation)*>
<!ELEMENT french (#PCDATA)>
<!ELEMENT entities (#PCDATA | maths | french)*>
<!ELEMENT evaluation (#PCDATA)> ]>

<entities>
    <maths>
        <expression>20 &gt; 50</expression>
        <evaluation>true</evaluation>
    </maths>
    <french>Il nous était très agréable d'aprendre que vous avez les numismatiques, mais il nous fachait bien de en même temps, que vous n'en possedez pas une épreuve. </french>
</entities>
